apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemini-ms-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: nodemini-ms-client
          image: gozie213/nodemini-ms-client
---
apiVersion: v1
kind: Service
metadata:
  name: nodemini-ms-client-clusterip
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
