apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemini-ms-posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: nodemini-ms-posts
          image: gozie213/nodemini-ms-posts
---
apiVersion: v1
kind: Service
metadata:
  name: nodemini-ms-posts-clustersrv
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
