apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemini-ms-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: nodemini-ms-query
          image: gozie213/nodemini-ms-query
---
apiVersion: v1
kind: Service
metadata:
  name: nodemini-ms-query-clusterip
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
